### ISSUE TITLE
Very slow in Chrome on Ubuntu 18.04 wiith GTX1080 and a 720p Logitech 720p camera

### ISSUE THREAD

**Issue by huan** [BrowseHandsfree/handsfreeJS#34]
When I visit https://handsfree.js.org and enable Web Camera, the average FPS I feel is <1. 

I think it should not so slow, is there anyone who had met the same issue before, and any solutions?

BTW: Thanks for this great project!

**Comment by labofoz** [comment]
Hi thanks for the feedback! Most likely this is due to a bunch of code I recently removed 😅


This library depends on [BRFv4](https://github.com/Tastenkunst/brfv4_javascript_examples), which comes in a WASM and ASM version. In order to keep filesize down, I removed the ASM because most current browsers can use the WASM version...but I also removed some of the logic that tests for these things. I'll try to put this code back, and then test it on an ubuntu.

If it's not that, then you might need to [enable Hardware Acceleration in Chrome](https://askubuntu.com/a/706329). In some previous versions of Ubuntu/Chrome, the GPU is disabled.

I'll fix by tomorrow. It's related to another issue where I will be adding a settings panel to help you adjust performance. Thanks again for the feedback!

**Comment by labofoz** [comment]
Hi thanks for the feedback! Most likely this is due to a bunch of code I recently removed 😅

This library depends on [BRFv4](https://github.com/Tastenkunst/brfv4_javascript_examples), which comes in a WASM and ASM version. In order to keep filesize down, I removed the ASM because most current browsers can use the WASM version...but I also removed some of the logic that tests for these things. I'll try to put this code back, and then test it on an ubuntu.

If it's not that, then you might need to [enable Hardware Acceleration in Chrome](https://askubuntu.com/a/706329). In some previous versions of Ubuntu/Chrome, the GPU is disabled.

I should have this fixed by tomorrow and will let you know if I find anything (I have an Ubuntu to test)

**Comment by huan** [comment]
Thanks for the tips!

I had just confirmed that my _Override software rendering list_ in Chrome is not enabled before. After I enabled it, the performance is better now: it's useable!

But it still feels not smooth enough, hope you will find something tomorrow, would love to hear from you back and looking forward to giving it another try!

**Comment by MarcelKlammer** [comment]
If the app is working, but just slowly, then WebAssembly is working. You could take a look at the CPU profile in Chome dev tools and show us a screenshot of a single frame and it's timeline.

**Comment by huan** [comment]
This is my screenshot, does that show what you need?

![image](https://user-images.githubusercontent.com/1361891/49171358-51934b00-f379-11e8-8a46-8c4f8ea3b5e1.png)

**Comment by MarcelKlammer** [comment]
It shows, that you get a frame rate of 30 and more... so something makes it feel like it's slow... so that's worth noting for Oz.

**Comment by labofoz** [comment]
Thanks for the screenshot, this is very helpful! I should have a fix to this in another few hours and will report back. I have a settings page that will let you turn off all the extra stuff (like the background animation).

Thank you both for helping!

**Comment by labofoz** [comment]
I've added a way to turn off the animated background, which I think is what's causing the performance issues. Click on the top left > Settings: https://handsfree.js.org/#/settings

![image](https://user-images.githubusercontent.com/42591975/49196599-643d5e00-f340-11e8-8690-7c0b435d1381.png)

If it still doesn't feel smooth enough, then I'll revisit this issue next week. I plan on doing some benchmarking, and I don't think I'll be able to help further until I understand how Handsfree.js performs in different browsers. I also will add more settings, which may also improve smoothness.

Thanks again!

**Comment by huan** [comment]
I tried the settings page and it seems that the performance is all ok with or without the animated background.

Cheers!
